image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build
          caches:
            - maven
          script:
            - mvn compile --file pom.xml
      - step:
          name: Test
          caches:
            - maven
          script:
            - mvn test test org.pitest:pitest-maven:mutationCoverage --file pom.xml
